### ISSUE TITLE
No idempotency

### ISSUE THREAD

**Issue by RyanMBess** [CiscoISE/ansible-ise#49]
Running playbooks should result in ansible tacking action on ise only once or when there's a change in the playbook.  I'm discovering that the ciscoISE's playbooks are NOT idempotent.  Thus everytime you run the playbook it actually makes the change even if it's alrady there.  Sometimes it just flat out fails such as in the creation of STG.  If you run the stg playbook > the stg is created.  You run it again, it bombs.

**Comment by RyanMBess** [comment]
please delete this i was reading the output wrong

**Comment by RyanMBess** [comment]
@wastorga  Actually please re-open this....not sure what i was looking at earlier to request it to be closed.  Not sure how many modules are impacted.  

When creating an endpoint with the attached create_endpoint playbook, the first time it will create the endpoint.  if you re-run it fails as it doesn't appear to check if the endpoint is there...it just tries to make the same endpoint. 
[create_endpoint_second_run.txt](https://github.com/CiscoISE/ansible-ise/files/9428683/create_endpoint_second_run.txt)
[create_endpoint_result.txt](https://github.com/CiscoISE/ansible-ise/files/9428684/create_endpoint_result.txt)
[create_endpoint.txt](https://github.com/CiscoISE/ansible-ise/files/9428685/create_endpoint.txt)

Same thing happens when you are doing STG's via an ansible playbook.  I've attached the sample STG playbook here as well so you can repo the issue (just run it twice against your ISE instance).   
[playbook_createstg.txt](https://github.com/CiscoISE/ansible-ise/files/9428700/playbook_createstg.txt)

**Comment by bvargasre** [comment]
Hi @RyanMBess
reviewing your playbook and api documentation `https://developer.cisco.com/docs/identity-services-engine/latest/#!endpoint`
I found the following:
The `name` field is the same as the `mac` field, that is why when searching it does not find it since there is none with the `name= Some device` and that is why it tries to create it again.
Apart from that, the `mac` has the following format= 00:00:00:00:00:00:00:00:00:00
Then the playbook would look something like this

``` yaml
- name: Create Endpoint
  cisco.ise.endpoint:
    ise_hostname: "{{ise_hostname}}"
    ise_username: "{{ise_username}}"
    ise_password: "{{ise_password}}"
    ise_verify: "{{ise_verify}}"
    state: present
    description:  test
    name: "50:00:00:01:00:14"
    mac: "50:00:00:01:00:14"
  register: result

**Comment by RyanMBess** [comment]
Morning @bvargasre,
What i'm trying to tell you is that with Ansible, you should be able to run the same commands over and over and over again and Ansible would only take action if the change is needed.  If you take your playbook in your last post and run it over and over you will see that upon the first time you run it, should the mac not be in ISE, the playbook will create it.  If you run it again, it will fail thus these modules you are providing are not idempotent.  Thus we should be able to create a long series of tasks that will ensure an endpoint remains in ISE as we would schedule a cron job to run every day that will go and look in ISE to ensure endpoints are all within ISE.  Thus we are doing true infrastructure as code that is keeping all our configs in playbooks, running them over and over and over again and if someone manually went into ISE and made a change that deviated from the playbooks (in this example, imagine someone went into ISE manually and deleted the endpoint 50:00:00:01:00:14 or even updated the description manually in ISE) once the playbook is re-ran, it would re-create the endpoint as per what is in the playbook.  Hopefully this helps.

**Comment by bvargasre** [comment]
Hi @RyanMBess , ansible-ise has been updated to version 2.5.3, so try this new version and tell me if it works.

For `endpoint`, the name field has been removed, since it is generated by the API using the mac parameter, generating confusion.
In fact in previous playbook according to the tests performed had no idempotency problems, but still to avoid problems of some of the behavior of the API the name field was removed.

The playbook would look like this:
``` yaml
- name: Create Endpoint
  cisco.ise.endpoint:
    ise_hostname: "{{ise_hostname}}"
    ise_username: "{{ise_username}}"
    ise_password: "{{ise_password}}"
    ise_verify: "{{ise_verify}}"
    state: present
    description:  desc
    mac: "50:00:00:01:00:14"
  register: result
