### ISSUE TITLE
Unable to create endpoint

### ISSUE THREAD

**Issue by ai-ryanbess** [CiscoISE/ansible-ise#84]
per https://docs.ansible.com/ansible/latest/collections/cisco/ise/endpoint_module.html, the name attribute is supported.  However when you go and use the name attribute, it errors out.  Please support being able to name endpoints as they are entered into ise via the API.  

    "msg": [
        "name. Supported parameters include: ise_hostname, identityStore, ise_username, ise_uses_csrf_token, staticProfileAssignment, ise_version, identityStoreId, description, portalUser, profileId, ise_password, mdmAttributes, mac, state, ise_verify, groupId, id, ise_debug, customAttributes, ise_uses_api_gateway, ise_wait_on_rate_limit, staticGroupAssignment."
    ]

**Comment by fmunozmiranda** [comment]
Hi, @ai-ryanbess, the attribute `name` was removed in a previous version, because is directly related with `mac` attribute, the value given to the `mac` attribute is the same as that taken by `name`, even if something else is sent by parameters, it omits it.

The documentation will be updated to temporarily remove the `name` attribute, due to its behavior in the supported API version (3.1.patch_1).
maybe in future versions, the `name` parameter will be part of the structure again.

**Comment by ai-ryanbess** [comment]
Thanks.  While i got you can you please provide me an example of a filter.  Example, how would i search ISE with the filter parameter to pull the endpoint that has mac 00:00:00:00:00:00

https://docs.ansible.com/ansible/latest/collections/cisco/ise/endpoint_info_module.html#parameter-filter

**Comment by htlgit00** [comment]
@ai-ryanbess I think this derived from ISE ERS / [endpoint](https://developer.cisco.com/docs/identity-services-engine/latest/#!endpoint) / GET /ers/config/endpoint
where gives the syntax as `/ers/config/endpoint?filter={filter name}.{operator}.{filter value}`

So, please try `mac.EQ.00:00:00:00:00:00`

**Comment by bvargasre** [comment]
I'm going to close this issue due to inactivity, in case you have any other questions feel free to reopen it or create a new one
Regards
